# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_dockerfile.ipynb.

# %% auto 0
__all__ = ['generate_dockerfile']

# %% ../../nbs/02_dockerfile.ipynb 3
import os
from pathlib import Path

from jinja2 import Environment

# %% ../../nbs/02_dockerfile.ipynb 5
def generate_dockerfile(
    gpu: bool = False, # Whether to make the GPU available
    deepstream: bool = False, # Whether to set up project for DeepStream
    project_directory: str = ".", # Where to create the dockerfile. Defaults to working directory.
    template_directory: str = ".", # Where to create the .devcontainer folder. Defaults to working directory.
) -> None:
    """
    Write a Dockerfile the project.

    Parameters
    ----------
    gpu
        Whether to make the GPU available
    deepstream
        Whether to set up project for DeepStream
    project_directory
        Where to create the dockerfile. Defaults to working directory.
    template_directory
        Where the template directory is located. Defaults to working directory.
    """
    env = Environment(autoescape=True)
    template_directory = Path(template_directory) / "templates"
    output_directory = Path(project_directory)
    template_variables = dict(gpu=gpu, deepstream=deepstream)
    for fname in os.listdir(template_directory):
        output_path = output_directory / fname
        with open(template_directory / fname) as f:
            template = env.from_string(f.read())
        with open(output_path, "w") as f:
            f.write(template.render(**template_variables))
